using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Faker.Core.Interfaces;
using Xunit;
using Moq;
using Lepesh.Lepesh;
using Faker.Core.Services;

namespace Lepesh.Lepesh.Tests
{
    class LepeshClassTests
    {
        LepeshClass _sut;

        LepeshClassTests()
        {
            _sut = new LepeshClass();
        }

        public void LepeshMethodTest()
        {

            void result = _sut.LepeshMethodTest();

            void expected = null;
            Assert.That(result, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        public void LepeshMethod2Test()
        {

            void result = _sut.LepeshMethod2Test();

            void expected = null;
            Assert.That(result, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}

namespace Faker.Core.Services.Tests
{
    class CycleResolveServiceTests
    {
        CycleResolveService _sut;

        CycleResolveServiceTests()
        {
            _sut = new CycleResolveService();
        }

        public void AddTest()
        {
            Type t = null;

            void result = _sut.AddTest(t);

            void expected = null;
            Assert.That(result, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        public void RemoveTest()
        {
            Type t = null;

            void result = _sut.RemoveTest(t);

            void expected = null;
            Assert.That(result, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        public void ContainsTest()
        {
            Type t = null;

            bool result = _sut.ContainsTest(t);

            bool expected = null;
            Assert.That(result, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        public void ClearTest()
        {

            void result = _sut.ClearTest();

            void expected = null;
            Assert.That(result, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}