using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Faker.Core.Interfaces;
using Xunit;
using Lepesh.Lepesh;
using Faker.Core.Services;

namespace Lepesh.Lepesh.Tests
{
    class LepeshClassTests
    {
    }
}

namespace Faker.Core.Services.Tests
{
    class CycleResolveServiceTests
    {
        public void AddTest()
        {
            Assert.Fail("autogenerated");
        }

        public void RemoveTest()
        {
            Assert.Fail("autogenerated");
        }

        public void ContainsTest()
        {
            Assert.Fail("autogenerated");
        }

        public void ClearTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}