using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Faker.Core.Interfaces;
using Xunit;
using Moq;
using Lepesh.Lepesh;
using Faker.Core.Services;

namespace Lepesh.Lepesh.Tests
{
    class LepeshClassTests
    {
        private LepeshClass _sut;

        LepeshClassTests()
        {
            var _sut = new LepeshClass();
        }

        public void LepeshMethodTest()
        {
            _sut.LepeshMethodTest();
            Assert.Fail("autogenerated");
        }

        public void LepeshMethod2Test()
        {
            _sut.LepeshMethod2Test();
            Assert.Fail("autogenerated");
        }
    }
}

namespace Faker.Core.Services.Tests
{
    class CycleResolveServiceTests
    {
        private CycleResolveService _sut;

        CycleResolveServiceTests()
        {
            var _sut = new CycleResolveService();
        }

        public void AddTest()
        {
            Type t = default;
            _sut.AddTest(t);
            Assert.Fail("autogenerated");
        }

        public void RemoveTest()
        {
            Type t = default;
            _sut.RemoveTest(t);
            Assert.Fail("autogenerated");
        }

        public void ContainsTest()
        {
            Type t = default;
            bool result = _sut.ContainsTest(t);
            bool expected = default;
            Assert.That(result, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        public void ClearTest()
        {
            _sut.ClearTest();
            Assert.Fail("autogenerated");
        }
    }
}