using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Faker.Core.Exceptions;
using Faker.Core.Interfaces;
using Faker.Core.Records;
using Xunit;
using Faker.Core.Services;

namespace Faker.Core.Services.Tests
{
    class GeneratorServiceTests
    {
        public void GenerateTest()
        {
            Assert.Fail("autogenerated");
        }

        public void InitializeGeneratorsTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}