using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Faker.Core.Exceptions;
using Faker.Core.Interfaces;
using Faker.Core.Records;
using Xunit;
using Moq;
using Faker.Core.Services;

namespace Faker.Core.Services.Tests
{
    class GeneratorServiceTests
    {
        GeneratorService _sut;
        Mock<IGeneratorConfig> _generatorConfig;

        GeneratorServiceTests()
        {
            _generatorConfig = new Mock<IGeneratorConfig>();
            _sut = new GeneratorService(_generatorConfig.Object);
        }

        public void GenerateTest()
        {
            Type type = null;
            IGeneratorContext context = null;
            string name = ;
            Type userType = null;

            object result = _sut.GenerateTest(type, context, name, userType);

            object expected = null;
            Assert.That(result, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        public void InitializeGeneratorsTest()
        {

            void result = _sut.InitializeGeneratorsTest();

            void expected = null;
            Assert.That(result, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}