using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xunit;
using Moq;
using TestsGenerator.Core.InputFiles;

namespace TestsGenerator.Core.InputFiles.Tests
{
    class TestClassTests
    {
        TestClass _sut;

        TestClassTests()
        {
            _sut = new TestClass();
        }

        public void TestMethodTest()
        {

            void result = _sut.TestMethodTest();

            void expected = null;
            Assert.That(result, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}