using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xunit;
using TestsGenerator.Core.InputFiles;

namespace TestsGenerator.Core.InputFiles.Tests
{
    class TestClassTests
    {
        public void TestMethodTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}