using DirectoryScanner.Application.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xunit;
using Moq;
using DirectoryScanner.Application.Services;

namespace DirectoryScanner.Application.Services.Tests
{
    class TreeTraverseServiceTests
    {
        TreeTraverseService _sut;

        TreeTraverseServiceTests()
        {
            _sut = new TreeTraverseService();
        }

        public void PostorderTraverseTest()
        {
            Tree tree = null;
            Action<Node> action = null;

            void result = _sut.PostorderTraverseTest(tree, action);

            void expected = null;
            Assert.That(result, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        public void RecursivePostorderTraverseTest()
        {
            Node node = null;
            Action<Node> action = null;

            void result = _sut.RecursivePostorderTraverseTest(node, action);

            void expected = null;
            Assert.That(result, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}