using DirectoryScanner.Application.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xunit;
using Moq;
using DirectoryScanner.Application.Services;

namespace DirectoryScanner.Application.Services.Tests
{
    class TreeTraverseServiceTests
    {
        private TreeTraverseService _sut;

        TreeTraverseServiceTests()
        {
            var _sut = new TreeTraverseService();
        }

        public void PostorderTraverseTest()
        {
            Tree tree = default;
            Action<Node> action = default;
            _sut.PostorderTraverseTest(tree, action);
            Assert.Fail("autogenerated");
        }

        public void RecursivePostorderTraverseTest()
        {
            Node node = default;
            Action<Node> action = default;
            _sut.RecursivePostorderTraverseTest(node, action);
            Assert.Fail("autogenerated");
        }
    }
}