using DirectoryScanner.Application.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xunit;
using DirectoryScanner.Application.Services;

namespace DirectoryScanner.Application.Services.Tests
{
    class TreeTraverseServiceTests
    {
        public void PostorderTraverseTest()
        {
            Assert.Fail("autogenerated");
        }

        public void RecursivePostorderTraverseTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}